// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_misused_spread

import "github.com/typescript-eslint/tsgolint/internal/utils"

type NoMisusedSpreadOptions struct {
	// Types to allow spreading in object or array/call expressions
	Allow []utils.TypeOrValueSpecifier `json:"allow,omitempty"`
}
