name: Setup

description: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod

    - uses: extractions/setup-crate@4993624604c307fbca528d28a3c8b60fa5ecc859 # v1.4.0
      with:
        repo: casey/just
        version: ${{ inputs.just-version }}
        github-token: ${{ inputs.github-token }}

    - name: Set committer identity
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"

    - name: Apply typescript-go patches
      shell: bash
      run: |
        pushd typescript-go
        git am --3way --no-gpg-sign ../patches/*.patch
        popd

    - name: Expose typescript-go collections package
      shell: bash
      run: |
        mkdir -p internal/collections
        find ./typescript-go/internal/collections -type f ! -name '*_test.go' -exec cp {} internal/collections/ \;
