name: Setup

description: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod

    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

    - name: Set committer identity
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"

    - name: Apply typescript-go patches
      shell: bash
      run: |
        pushd typescript-go
        git am --3way --no-gpg-sign ../patches/*.patch
        popd

    - name: Expose typescript-go collections package
      shell: bash
      run: |
        mkdir -p internal/collections
        find ./typescript-go/internal/collections -type f ! -name '*_test.go' -exec cp {} internal/collections/ \;
