# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  allow-parallel-runners: true

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - depguard
    - durationcheck
    # - errcheck # TODO
    - errchkjson
    - errname
    - errorlint #TODO
    - fatcontext
    - gocheckcompilerdirectives
    - goprintffuncname
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nolintlint
    # - paralleltest # TODO
    - perfsprint
    - predeclared
    - reassign
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - goheader
    # - exhaustive # TODO
    # - gocritic # TODO
    # - gosec # TODO
    # - revive # TODO
    # - staticcheck # TODO
    - testifylint
    - unparam # TODO
    - unused # TODO

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "encoding/json$"
              desc: 'Use "github.com/go-json-experiment/json" instead.'

  exclusions:
    presets:
      - comments
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
