
// Code generated by tools/gen_shims. DO NOT EDIT.

package pnpvfs

import "github.com/microsoft/typescript-go/internal/vfs"
import _ "github.com/microsoft/typescript-go/internal/vfs/pnpvfs"
import _ "unsafe"

//go:linkname From github.com/microsoft/typescript-go/internal/vfs/pnpvfs.From
func From(fs vfs.FS) vfs.FS
