
// Code generated by tools/gen_shims. DO NOT EDIT.

package contentmapper

import "context"
import "github.com/microsoft/TypeScript/tsc/internal/ast"
import "github.com/microsoft/TypeScript/tsc/internal/contentmapper"
import "github.com/microsoft/TypeScript/tsc/internal/locale"
import _ "unsafe"

//go:linkname CheckSupplementalFileNameCollisions github.com/microsoft/TypeScript/tsc/internal/contentmapper.CheckSupplementalFileNameCollisions
func CheckSupplementalFileNameCollisions(files contentmapper.SourceFiles, fileExists func(string) bool) error
type CloseProjectParams = contentmapper.CloseProjectParams
type Definition = contentmapper.Definition
type Diagnostic = contentmapper.Diagnostic
type DiagnosticDirectiveError = contentmapper.DiagnosticDirectiveError
type DiagnosticDirectiveErrorKind = contentmapper.DiagnosticDirectiveErrorKind
const DiagnosticDirectiveErrorKindExpectMissingUnusedDiagnostic = contentmapper.DiagnosticDirectiveErrorKindExpectMissingUnusedDiagnostic
const DiagnosticDirectiveErrorKindInvalidPolicy = contentmapper.DiagnosticDirectiveErrorKindInvalidPolicy
const DiagnosticDirectiveErrorKindInvalidRange = contentmapper.DiagnosticDirectiveErrorKindInvalidRange
const DiagnosticDirectiveErrorKindInvalidUnusedDiagnosticIndex = contentmapper.DiagnosticDirectiveErrorKindInvalidUnusedDiagnosticIndex
const DiagnosticDirectiveErrorKindOverlap = contentmapper.DiagnosticDirectiveErrorKindOverlap
type DiagnosticDirectivePolicy = contentmapper.DiagnosticDirectivePolicy
const DiagnosticDirectivePolicyExpect = contentmapper.DiagnosticDirectivePolicyExpect
const DiagnosticDirectivePolicyIgnore = contentmapper.DiagnosticDirectivePolicyIgnore
type DiagnosticDirectives = contentmapper.DiagnosticDirectives
var ErrProjectUnavailable = contentmapper.ErrProjectUnavailable
type Host = contentmapper.Host
type HostOptions = contentmapper.HostOptions
type InitializeError = contentmapper.InitializeError
type InitializeErrorKind = contentmapper.InitializeErrorKind
const InitializeErrorKindEmptyDiagnosticSource = contentmapper.InitializeErrorKindEmptyDiagnosticSource
const InitializeErrorKindInvalidResponse = contentmapper.InitializeErrorKindInvalidResponse
const InitializeErrorKindNoResponse = contentmapper.InitializeErrorKindNoResponse
const InitializeErrorKindPositionEncoding = contentmapper.InitializeErrorKindPositionEncoding
const InitializeErrorKindProcessExit = contentmapper.InitializeErrorKindProcessExit
const InitializeErrorKindProcessStart = contentmapper.InitializeErrorKindProcessStart
const InitializeErrorKindProtocolVersion = contentmapper.InitializeErrorKindProtocolVersion
const InitializeErrorKindRequest = contentmapper.InitializeErrorKindRequest
const InitializeErrorKindReservedDiagnosticSource = contentmapper.InitializeErrorKindReservedDiagnosticSource
type InitializeParams = contentmapper.InitializeParams
type InitializeResult = contentmapper.InitializeResult
type InvalidVirtualExtensionError = contentmapper.InvalidVirtualExtensionError
//go:linkname IsSupportedVirtualExtension github.com/microsoft/TypeScript/tsc/internal/contentmapper.IsSupportedVirtualExtension
func IsSupportedVirtualExtension(extension string) bool
type Logger = contentmapper.Logger
type Manifest = contentmapper.Manifest
type MappedDiagnosticDirective = contentmapper.MappedDiagnosticDirective
type MappedOutput = contentmapper.MappedOutput
type MappedResult = contentmapper.MappedResult
type Mapper = contentmapper.Mapper
type MapperTimings = contentmapper.MapperTimings
const MethodCloseProject = contentmapper.MethodCloseProject
const MethodInitialize = contentmapper.MethodInitialize
const MethodOpenProject = contentmapper.MethodOpenProject
const MethodTransform = contentmapper.MethodTransform
//go:linkname NewHost github.com/microsoft/TypeScript/tsc/internal/contentmapper.NewHost
func NewHost(ctx context.Context, spawner contentmapper.Spawner, diagnosticLocale locale.Locale) contentmapper.Host
//go:linkname NewHostWithOptions github.com/microsoft/TypeScript/tsc/internal/contentmapper.NewHostWithOptions
func NewHostWithOptions(ctx context.Context, spawner contentmapper.Spawner, diagnosticLocale locale.Locale, options contentmapper.HostOptions) contentmapper.Host
type OpenProjectParams = contentmapper.OpenProjectParams
type OpenProjectResult = contentmapper.OpenProjectResult
type OperationTiming = contentmapper.OperationTiming
type OptionDiagnostic = contentmapper.OptionDiagnostic
type OptionDiagnosticResult = contentmapper.OptionDiagnosticResult
type OptionPathSegment = contentmapper.OptionPathSegment
//go:linkname ParseResult github.com/microsoft/TypeScript/tsc/internal/contentmapper.ParseResult
func ParseResult(parseOptions ast.SourceFileParseOptions, content string, mapper *contentmapper.Mapper, transformIdentity string, result contentmapper.Result) (contentmapper.SourceFiles, error)
type PositionEncoding = contentmapper.PositionEncoding
const PositionEncodingUTF16 = contentmapper.PositionEncodingUTF16
const PositionEncodingUTF8 = contentmapper.PositionEncodingUTF8
type Project = contentmapper.Project
type ProjectError = contentmapper.ProjectError
type ProjectErrorKind = contentmapper.ProjectErrorKind
const ProjectErrorKindMalformedResponse = contentmapper.ProjectErrorKindMalformedResponse
const ProjectErrorKindMissingConfigIdentity = contentmapper.ProjectErrorKindMissingConfigIdentity
const ProjectErrorKindNonAbsoluteWatchedFile = contentmapper.ProjectErrorKindNonAbsoluteWatchedFile
const ProjectErrorKindUnexpectedConfigIdentity = contentmapper.ProjectErrorKindUnexpectedConfigIdentity
const ProjectErrorKindUnexpectedWatchedFiles = contentmapper.ProjectErrorKindUnexpectedWatchedFiles
type ProjectSpec = contentmapper.ProjectSpec
const ProtocolVersion = contentmapper.ProtocolVersion
type Request = contentmapper.Request
type Result = contentmapper.Result
type SourceFiles = contentmapper.SourceFiles
type Spawner = contentmapper.Spawner
type SpawnerFunc = contentmapper.SpawnerFunc
type SupplementalFileCollisionError = contentmapper.SupplementalFileCollisionError
type SupplementalOutput = contentmapper.SupplementalOutput
type Timings = contentmapper.Timings
//go:linkname TransformAndParse github.com/microsoft/TypeScript/tsc/internal/contentmapper.TransformAndParse
func TransformAndParse(parseOptions ast.SourceFileParseOptions, content string, mapper *contentmapper.Mapper, project contentmapper.Project) (contentmapper.SourceFiles, error)
type TransformError = contentmapper.TransformError
type TransformErrorKind = contentmapper.TransformErrorKind
const TransformErrorKindInitialize = contentmapper.TransformErrorKindInitialize
const TransformErrorKindMappings = contentmapper.TransformErrorKindMappings
const TransformErrorKindProject = contentmapper.TransformErrorKindProject
const TransformErrorKindRequest = contentmapper.TransformErrorKindRequest
const TransformErrorKindResponse = contentmapper.TransformErrorKindResponse
const TransformErrorKindUnknown = contentmapper.TransformErrorKindUnknown
type TransformParams = contentmapper.TransformParams
type TransformResult = contentmapper.TransformResult
type UnusedExpectDirectiveDiagnostic = contentmapper.UnusedExpectDirectiveDiagnostic
