// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_object_comparison

import "github.com/go-json-experiment/json"

type NoObjectComparisonOptions struct {
	// ClassNames corresponds to the JSON schema field "classNames".
	ClassNames []string `json:"classNames,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoObjectComparisonOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoObjectComparisonOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["classNames"]; !ok || v == nil {
		plain.ClassNames = []string{}
	}
	*j = NoObjectComparisonOptions(plain)
	return nil
}
