// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_optional_chain

import "github.com/go-json-experiment/json"

type PreferOptionalChainOptions struct {
	// AllowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing corresponds
	// to the JSON schema field
	// "allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing".
	AllowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing bool `json:"allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing,omitempty"`

	// CheckAny corresponds to the JSON schema field "checkAny".
	CheckAny bool `json:"checkAny,omitempty"`

	// CheckBigInt corresponds to the JSON schema field "checkBigInt".
	CheckBigInt bool `json:"checkBigInt,omitempty"`

	// CheckBoolean corresponds to the JSON schema field "checkBoolean".
	CheckBoolean bool `json:"checkBoolean,omitempty"`

	// CheckNumber corresponds to the JSON schema field "checkNumber".
	CheckNumber bool `json:"checkNumber,omitempty"`

	// CheckString corresponds to the JSON schema field "checkString".
	CheckString bool `json:"checkString,omitempty"`

	// CheckUnknown corresponds to the JSON schema field "checkUnknown".
	CheckUnknown bool `json:"checkUnknown,omitempty"`

	// RequireNullish corresponds to the JSON schema field "requireNullish".
	RequireNullish bool `json:"requireNullish,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferOptionalChainOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferOptionalChainOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing"]; !ok || v == nil {
		plain.AllowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing = false
	}
	if v, ok := raw["checkAny"]; !ok || v == nil {
		plain.CheckAny = true
	}
	if v, ok := raw["checkBigInt"]; !ok || v == nil {
		plain.CheckBigInt = true
	}
	if v, ok := raw["checkBoolean"]; !ok || v == nil {
		plain.CheckBoolean = true
	}
	if v, ok := raw["checkNumber"]; !ok || v == nil {
		plain.CheckNumber = true
	}
	if v, ok := raw["checkString"]; !ok || v == nil {
		plain.CheckString = true
	}
	if v, ok := raw["checkUnknown"]; !ok || v == nil {
		plain.CheckUnknown = true
	}
	if v, ok := raw["requireNullish"]; !ok || v == nil {
		plain.RequireNullish = false
	}
	*j = PreferOptionalChainOptions(plain)
	return nil
}
