// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package consistent_return

import "encoding/json"

type ConsistentReturnOptions struct {
	// Whether to treat `undefined` as an unspecified return value
	TreatUndefinedAsUnspecified bool `json:"treatUndefinedAsUnspecified,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConsistentReturnOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ConsistentReturnOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["treatUndefinedAsUnspecified"]; !ok || v == nil {
		plain.TreatUndefinedAsUnspecified = false
	}
	*j = ConsistentReturnOptions(plain)
	return nil
}
