// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package naming_convention

import "github.com/go-json-experiment/json"
import "fmt"
import "reflect"

type NamingConventionFormat string

const NamingConventionFormatCamelCase NamingConventionFormat = "camelCase"
const NamingConventionFormatPascalCase NamingConventionFormat = "PascalCase"
const NamingConventionFormatSnakeCase NamingConventionFormat = "snake_case"
const NamingConventionFormatStrictCamelCase NamingConventionFormat = "strictCamelCase"
const NamingConventionFormatStrictPascalCase NamingConventionFormat = "StrictPascalCase"
const NamingConventionFormatUPPERCASE NamingConventionFormat = "UPPER_CASE"

var enumValues_NamingConventionFormat = []interface{}{
	"camelCase",
	"strictCamelCase",
	"PascalCase",
	"StrictPascalCase",
	"snake_case",
	"UPPER_CASE",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionFormat) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NamingConventionFormat {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NamingConventionFormat, v)
	}
	*j = NamingConventionFormat(v)
	return nil
}

type NamingConventionMatchRegex struct {
	// Whether the identifier must match (`true`) or must not match (`false`) the
	// regex.
	Match bool `json:"match"`

	// The regular expression source.
	Regex string `json:"regex"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionMatchRegex) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["match"]; raw != nil && !ok {
		return fmt.Errorf("field match in NamingConventionMatchRegex: required")
	}
	if _, ok := raw["regex"]; raw != nil && !ok {
		return fmt.Errorf("field regex in NamingConventionMatchRegex: required")
	}
	type Plain NamingConventionMatchRegex
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NamingConventionMatchRegex(plain)
	return nil
}

type NamingConventionModifier string

const NamingConventionModifierAbstract NamingConventionModifier = "abstract"
const NamingConventionModifierAsync NamingConventionModifier = "async"
const NamingConventionModifierConst NamingConventionModifier = "const"
const NamingConventionModifierDefault NamingConventionModifier = "default"
const NamingConventionModifierDestructured NamingConventionModifier = "destructured"
const NamingConventionModifierExported NamingConventionModifier = "exported"
const NamingConventionModifierGlobal NamingConventionModifier = "global"
const NamingConventionModifierNamespace NamingConventionModifier = "namespace"
const NamingConventionModifierOverride NamingConventionModifier = "override"
const NamingConventionModifierPrivate NamingConventionModifier = "private"
const NamingConventionModifierProtected NamingConventionModifier = "protected"
const NamingConventionModifierPublic NamingConventionModifier = "public"
const NamingConventionModifierReadonly NamingConventionModifier = "readonly"
const NamingConventionModifierRequiresQuotes NamingConventionModifier = "requiresQuotes"
const NamingConventionModifierStatic NamingConventionModifier = "static"
const NamingConventionModifierUnused NamingConventionModifier = "unused"

var enumValues_NamingConventionModifier = []interface{}{
	"const",
	"readonly",
	"static",
	"public",
	"protected",
	"private",
	"#private",
	"abstract",
	"destructured",
	"global",
	"exported",
	"unused",
	"requiresQuotes",
	"override",
	"async",
	"default",
	"namespace",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionModifier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NamingConventionModifier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NamingConventionModifier, v)
	}
	*j = NamingConventionModifier(v)
	return nil
}

// An array of naming convention selectors. Each selector describes a naming
// convention for a set of identifiers.
type NamingConventionOptions []NamingConventionSelector

// A naming convention applied to the identifiers matched by `selector`,
// `modifiers`, `types` and `filter`.
type NamingConventionSelector struct {
	// A custom regex that the identifier must (or must not) match.
	Custom *NamingConventionMatchRegex `json:"custom,omitempty"`

	// Unused. Accepted for compatibility with typescript-eslint.
	FailureMessage *string `json:"failureMessage,omitempty"`

	// Controls whether this convention applies to an identifier. A string is treated
	// as `{ regex: string, match: true }`.
	Filter interface{} `json:"filter,omitempty"`

	// The allowed formats for the identifier. `null` (or an empty array) disables the
	// format check.
	Format interface{} `json:"format,omitempty"`

	// Whether leading underscores are allowed, forbidden or required.
	LeadingUnderscore *NamingConventionUnderscoreOption `json:"leadingUnderscore,omitempty"`

	// Modifiers that the identifier must have (all of them) for this convention to
	// apply.
	Modifiers []NamingConventionModifier `json:"modifiers,omitempty"`

	// Prefixes, one of which the identifier must start with.
	Prefix []string `json:"prefix,omitempty"`

	// One selector, or an array of selectors, that this convention applies to.
	Selector interface{} `json:"selector"`

	// Suffixes, one of which the identifier must end with.
	Suffix []string `json:"suffix,omitempty"`

	// Whether trailing underscores are allowed, forbidden or required.
	TrailingUnderscore *NamingConventionUnderscoreOption `json:"trailingUnderscore,omitempty"`

	// Types, one of which the identifier must have, for this convention to apply.
	// Requires type information.
	Types []NamingConventionTypeModifier `json:"types,omitempty"`
}

type NamingConventionSelectorName string

const NamingConventionSelectorNameAccessor NamingConventionSelectorName = "accessor"
const NamingConventionSelectorNameAutoAccessor NamingConventionSelectorName = "autoAccessor"
const NamingConventionSelectorNameClass NamingConventionSelectorName = "class"
const NamingConventionSelectorNameClassMethod NamingConventionSelectorName = "classMethod"
const NamingConventionSelectorNameClassProperty NamingConventionSelectorName = "classProperty"
const NamingConventionSelectorNameClassicAccessor NamingConventionSelectorName = "classicAccessor"
const NamingConventionSelectorNameDefault NamingConventionSelectorName = "default"
const NamingConventionSelectorNameEnum NamingConventionSelectorName = "enum"
const NamingConventionSelectorNameEnumMember NamingConventionSelectorName = "enumMember"
const NamingConventionSelectorNameFunction NamingConventionSelectorName = "function"
const NamingConventionSelectorNameImport NamingConventionSelectorName = "import"
const NamingConventionSelectorNameInterface NamingConventionSelectorName = "interface"
const NamingConventionSelectorNameMemberLike NamingConventionSelectorName = "memberLike"
const NamingConventionSelectorNameMethod NamingConventionSelectorName = "method"
const NamingConventionSelectorNameObjectLiteralMethod NamingConventionSelectorName = "objectLiteralMethod"
const NamingConventionSelectorNameObjectLiteralProperty NamingConventionSelectorName = "objectLiteralProperty"
const NamingConventionSelectorNameParameter NamingConventionSelectorName = "parameter"
const NamingConventionSelectorNameParameterProperty NamingConventionSelectorName = "parameterProperty"
const NamingConventionSelectorNameProperty NamingConventionSelectorName = "property"
const NamingConventionSelectorNameTypeAlias NamingConventionSelectorName = "typeAlias"
const NamingConventionSelectorNameTypeLike NamingConventionSelectorName = "typeLike"
const NamingConventionSelectorNameTypeMethod NamingConventionSelectorName = "typeMethod"
const NamingConventionSelectorNameTypeParameter NamingConventionSelectorName = "typeParameter"
const NamingConventionSelectorNameTypeProperty NamingConventionSelectorName = "typeProperty"
const NamingConventionSelectorNameVariable NamingConventionSelectorName = "variable"
const NamingConventionSelectorNameVariableLike NamingConventionSelectorName = "variableLike"

var enumValues_NamingConventionSelectorName = []interface{}{
	"default",
	"variableLike",
	"memberLike",
	"typeLike",
	"method",
	"property",
	"accessor",
	"variable",
	"function",
	"parameter",
	"parameterProperty",
	"classicAccessor",
	"enumMember",
	"classMethod",
	"objectLiteralMethod",
	"typeMethod",
	"classProperty",
	"objectLiteralProperty",
	"typeProperty",
	"autoAccessor",
	"class",
	"interface",
	"typeAlias",
	"enum",
	"typeParameter",
	"import",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionSelectorName) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NamingConventionSelectorName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NamingConventionSelectorName, v)
	}
	*j = NamingConventionSelectorName(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionSelector) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["selector"]; raw != nil && !ok {
		return fmt.Errorf("field selector in NamingConventionSelector: required")
	}
	type Plain NamingConventionSelector
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NamingConventionSelector(plain)
	return nil
}

type NamingConventionTypeModifier string

const NamingConventionTypeModifierArray NamingConventionTypeModifier = "array"
const NamingConventionTypeModifierBoolean NamingConventionTypeModifier = "boolean"
const NamingConventionTypeModifierFunction NamingConventionTypeModifier = "function"
const NamingConventionTypeModifierNumber NamingConventionTypeModifier = "number"
const NamingConventionTypeModifierString NamingConventionTypeModifier = "string"

var enumValues_NamingConventionTypeModifier = []interface{}{
	"boolean",
	"string",
	"number",
	"function",
	"array",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionTypeModifier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NamingConventionTypeModifier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NamingConventionTypeModifier, v)
	}
	*j = NamingConventionTypeModifier(v)
	return nil
}

type NamingConventionUnderscoreOption string

const NamingConventionUnderscoreOptionAllow NamingConventionUnderscoreOption = "allow"
const NamingConventionUnderscoreOptionAllowDouble NamingConventionUnderscoreOption = "allowDouble"
const NamingConventionUnderscoreOptionAllowSingleOrDouble NamingConventionUnderscoreOption = "allowSingleOrDouble"
const NamingConventionUnderscoreOptionForbid NamingConventionUnderscoreOption = "forbid"
const NamingConventionUnderscoreOptionRequire NamingConventionUnderscoreOption = "require"
const NamingConventionUnderscoreOptionRequireDouble NamingConventionUnderscoreOption = "requireDouble"

var enumValues_NamingConventionUnderscoreOption = []interface{}{
	"forbid",
	"allow",
	"require",
	"requireDouble",
	"allowDouble",
	"allowSingleOrDouble",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamingConventionUnderscoreOption) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NamingConventionUnderscoreOption {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NamingConventionUnderscoreOption, v)
	}
	*j = NamingConventionUnderscoreOption(v)
	return nil
}
