// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_unnecessary_type_assertion

import "github.com/go-json-experiment/json"

type NoUnnecessaryTypeAssertionOptions struct {
	// TypesToIgnore corresponds to the JSON schema field "typesToIgnore".
	TypesToIgnore []string `json:"typesToIgnore,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUnnecessaryTypeAssertionOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUnnecessaryTypeAssertionOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["typesToIgnore"]; !ok || v == nil {
		plain.TypesToIgnore = []string{}
	}
	*j = NoUnnecessaryTypeAssertionOptions(plain)
	return nil
}
