// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_useless_default_assignment

import "github.com/go-json-experiment/json"

type NoUselessDefaultAssignmentOptions struct {
	// Unless this is set to `true`, the rule will error on every file whose
	// `tsconfig.json` does _not_ have the `strictNullChecks` compiler option (or
	// `strict`) set to `true`.
	AllowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing bool `json:"allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUselessDefaultAssignmentOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUselessDefaultAssignmentOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing"]; !ok || v == nil {
		plain.AllowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing = false
	}
	*j = NoUselessDefaultAssignmentOptions(plain)
	return nil
}
