// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_invalid_void_type

import "github.com/go-json-experiment/json"

type NoInvalidVoidTypeOptions struct {
	// Whether a `this` parameter of a function may be `void`.
	AllowAsThisParameter bool `json:"allowAsThisParameter,omitempty"`

	// Whether `void` can be used as a valid value for generic type parameters.
	AllowInGenericTypeArguments interface{} `json:"allowInGenericTypeArguments,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoInvalidVoidTypeOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoInvalidVoidTypeOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowAsThisParameter"]; !ok || v == nil {
		plain.AllowAsThisParameter = false
	}
	if v, ok := raw["allowInGenericTypeArguments"]; !ok || v == nil {
		plain.AllowInGenericTypeArguments = true
	}
	*j = NoInvalidVoidTypeOptions(plain)
	return nil
}
