// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package restrict_template_expressions

import "encoding/json"
import "fmt"

// Describes specific types or values declared in local files.
type FileSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the type or value to match
	Name interface{} `json:"name"`

	// Optional file path to specify where the types or values must be declared. If
	// omitted, all files will be matched.
	Path *string `json:"path,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FileSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in FileSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in FileSpecifier: required")
	}
	type Plain FileSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FileSpecifier(plain)
	return nil
}

// Describes specific types or values declared in TypeScript's built-in lib.*.d.ts
// types.
type LibSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the lib type or value to match
	Name interface{} `json:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in LibSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LibSpecifier: required")
	}
	type Plain LibSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LibSpecifier(plain)
	return nil
}

// Describes specific types or values imported from packages.
type PackageSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the type or value to match
	Name interface{} `json:"name"`

	// The package name to match
	Package string `json:"package"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PackageSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in PackageSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PackageSpecifier: required")
	}
	if _, ok := raw["package"]; raw != nil && !ok {
		return fmt.Errorf("field package in PackageSpecifier: required")
	}
	type Plain PackageSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PackageSpecifier(plain)
	return nil
}

type RestrictTemplateExpressionsOptions struct {
	// Allow corresponds to the JSON schema field "allow".
	Allow []RestrictTemplateExpressionsOptionsAllowElem `json:"allow"`

	// AllowAny corresponds to the JSON schema field "allowAny".
	AllowAny bool `json:"allowAny,omitempty"`

	// AllowArray corresponds to the JSON schema field "allowArray".
	AllowArray bool `json:"allowArray,omitempty"`

	// AllowBoolean corresponds to the JSON schema field "allowBoolean".
	AllowBoolean bool `json:"allowBoolean,omitempty"`

	// AllowNever corresponds to the JSON schema field "allowNever".
	AllowNever bool `json:"allowNever,omitempty"`

	// AllowNullish corresponds to the JSON schema field "allowNullish".
	AllowNullish bool `json:"allowNullish,omitempty"`

	// AllowNumber corresponds to the JSON schema field "allowNumber".
	AllowNumber bool `json:"allowNumber,omitempty"`

	// AllowRegExp corresponds to the JSON schema field "allowRegExp".
	AllowRegExp bool `json:"allowRegExp,omitempty"`
}

type RestrictTemplateExpressionsOptionsAllowElem interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RestrictTemplateExpressionsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain RestrictTemplateExpressionsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []RestrictTemplateExpressionsOptionsAllowElem{
			map[string]interface{}{
				"from": "lib",
				"name": []interface{}{
					"Error",
					"URL",
					"URLSearchParams",
				},
			},
		}
	}
	if v, ok := raw["allowAny"]; !ok || v == nil {
		plain.AllowAny = true
	}
	if v, ok := raw["allowArray"]; !ok || v == nil {
		plain.AllowArray = false
	}
	if v, ok := raw["allowBoolean"]; !ok || v == nil {
		plain.AllowBoolean = true
	}
	if v, ok := raw["allowNever"]; !ok || v == nil {
		plain.AllowNever = false
	}
	if v, ok := raw["allowNullish"]; !ok || v == nil {
		plain.AllowNullish = true
	}
	if v, ok := raw["allowNumber"]; !ok || v == nil {
		plain.AllowNumber = true
	}
	if v, ok := raw["allowRegExp"]; !ok || v == nil {
		plain.AllowRegExp = true
	}
	*j = RestrictTemplateExpressionsOptions(plain)
	return nil
}

type TypeOrValueSpecifier interface{}
