// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package only_throw_error

import "encoding/json"
import "fmt"

// Describes specific types or values declared in local files.
type FileSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the type or value to match
	Name interface{} `json:"name"`

	// Optional file path to specify where the types or values must be declared. If
	// omitted, all files will be matched.
	Path *string `json:"path,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FileSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in FileSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in FileSpecifier: required")
	}
	type Plain FileSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FileSpecifier(plain)
	return nil
}

// Describes specific types or values declared in TypeScript's built-in lib.*.d.ts
// types.
type LibSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the lib type or value to match
	Name interface{} `json:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in LibSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LibSpecifier: required")
	}
	type Plain LibSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LibSpecifier(plain)
	return nil
}

type OnlyThrowErrorOptions struct {
	// An array of type or value specifiers which are allowed to be thrown
	Allow []OnlyThrowErrorOptionsAllowElem `json:"allow,omitempty"`

	// Whether to allow throwing values typed as any
	AllowThrowingAny bool `json:"allowThrowingAny,omitempty"`

	// Whether to allow throwing values typed as unknown
	AllowThrowingUnknown bool `json:"allowThrowingUnknown,omitempty"`
}

type OnlyThrowErrorOptionsAllowElem interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OnlyThrowErrorOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain OnlyThrowErrorOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []OnlyThrowErrorOptionsAllowElem{}
	}
	if v, ok := raw["allowThrowingAny"]; !ok || v == nil {
		plain.AllowThrowingAny = true
	}
	if v, ok := raw["allowThrowingUnknown"]; !ok || v == nil {
		plain.AllowThrowingUnknown = true
	}
	*j = OnlyThrowErrorOptions(plain)
	return nil
}

// Describes specific types or values imported from packages.
type PackageSpecifier struct {
	// From corresponds to the JSON schema field "from".
	From string `json:"from"`

	// The name(s) of the type or value to match
	Name interface{} `json:"name"`

	// The package name to match
	Package string `json:"package"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PackageSpecifier) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in PackageSpecifier: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PackageSpecifier: required")
	}
	if _, ok := raw["package"]; raw != nil && !ok {
		return fmt.Errorf("field package in PackageSpecifier: required")
	}
	type Plain PackageSpecifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PackageSpecifier(plain)
	return nil
}

type TypeOrValueSpecifier interface{}
