// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package only_throw_error

import "github.com/go-json-experiment/json"
import "github.com/typescript-eslint/tsgolint/internal/utils"

type OnlyThrowErrorOptions struct {
	// An array of type or value specifiers which are allowed to be thrown
	Allow []OnlyThrowErrorOptionsAllowElem `json:"allow,omitempty"`

	// Whether to allow throwing values typed as any
	AllowThrowingAny bool `json:"allowThrowingAny,omitempty"`

	// Whether to allow throwing values typed as unknown
	AllowThrowingUnknown bool `json:"allowThrowingUnknown,omitempty"`
}

type OnlyThrowErrorOptionsAllowElem = utils.TypeOrValueSpecifier

// UnmarshalJSON implements json.Unmarshaler.
func (j *OnlyThrowErrorOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain OnlyThrowErrorOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []OnlyThrowErrorOptionsAllowElem{}
	}
	if v, ok := raw["allowThrowingAny"]; !ok || v == nil {
		plain.AllowThrowingAny = true
	}
	if v, ok := raw["allowThrowingUnknown"]; !ok || v == nil {
		plain.AllowThrowingUnknown = true
	}
	*j = OnlyThrowErrorOptions(plain)
	return nil
}
