// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_nullish_coalescing

import "github.com/go-json-experiment/json"

type PreferNullishCoalescingOptions struct {
	// AllowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing corresponds to the JSON
	// schema field "allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing".
	AllowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing bool `json:"allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing,omitempty"`

	// IgnoreBooleanCoercion corresponds to the JSON schema field
	// "ignoreBooleanCoercion".
	IgnoreBooleanCoercion bool `json:"ignoreBooleanCoercion,omitempty"`

	// IgnoreConditionalTests corresponds to the JSON schema field
	// "ignoreConditionalTests".
	IgnoreConditionalTests bool `json:"ignoreConditionalTests,omitempty"`

	// IgnoreIfStatements corresponds to the JSON schema field "ignoreIfStatements".
	IgnoreIfStatements bool `json:"ignoreIfStatements,omitempty"`

	// IgnoreMixedLogicalExpressions corresponds to the JSON schema field
	// "ignoreMixedLogicalExpressions".
	IgnoreMixedLogicalExpressions bool `json:"ignoreMixedLogicalExpressions,omitempty"`

	// IgnorePrimitives corresponds to the JSON schema field "ignorePrimitives".
	IgnorePrimitives *PreferNullishCoalescingOptionsIgnorePrimitives `json:"ignorePrimitives,omitempty"`

	// IgnoreTernaryTests corresponds to the JSON schema field "ignoreTernaryTests".
	IgnoreTernaryTests bool `json:"ignoreTernaryTests,omitempty"`
}

type PreferNullishCoalescingOptionsIgnorePrimitives struct {
	// Bigint corresponds to the JSON schema field "bigint".
	Bigint bool `json:"bigint,omitempty"`

	// Boolean corresponds to the JSON schema field "boolean".
	Boolean bool `json:"boolean,omitempty"`

	// Number corresponds to the JSON schema field "number".
	Number bool `json:"number,omitempty"`

	// String corresponds to the JSON schema field "string".
	String bool `json:"string,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferNullishCoalescingOptionsIgnorePrimitives) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferNullishCoalescingOptionsIgnorePrimitives
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["bigint"]; !ok || v == nil {
		plain.Bigint = false
	}
	if v, ok := raw["boolean"]; !ok || v == nil {
		plain.Boolean = false
	}
	if v, ok := raw["number"]; !ok || v == nil {
		plain.Number = false
	}
	if v, ok := raw["string"]; !ok || v == nil {
		plain.String = false
	}
	*j = PreferNullishCoalescingOptionsIgnorePrimitives(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferNullishCoalescingOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferNullishCoalescingOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing"]; !ok || v == nil {
		plain.AllowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing = false
	}
	if v, ok := raw["ignoreBooleanCoercion"]; !ok || v == nil {
		plain.IgnoreBooleanCoercion = false
	}
	if v, ok := raw["ignoreConditionalTests"]; !ok || v == nil {
		plain.IgnoreConditionalTests = true
	}
	if v, ok := raw["ignoreIfStatements"]; !ok || v == nil {
		plain.IgnoreIfStatements = false
	}
	if v, ok := raw["ignoreMixedLogicalExpressions"]; !ok || v == nil {
		plain.IgnoreMixedLogicalExpressions = false
	}
	if v, ok := raw["ignoreTernaryTests"]; !ok || v == nil {
		plain.IgnoreTernaryTests = false
	}
	*j = PreferNullishCoalescingOptions(plain)
	return nil
}
