// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_useless_coalescing

import "github.com/go-json-experiment/json"

type NoUselessCoalescingOptions struct {
	// Whether to also report `|| undefined` fallbacks that normalize falsy values on
	// nullish-capable primitive types.
	DetectFalsyValues bool `json:"detectFalsyValues,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoUselessCoalescingOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoUselessCoalescingOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["detectFalsyValues"]; !ok || v == nil {
		plain.DetectFalsyValues = false
	}
	*j = NoUselessCoalescingOptions(plain)
	return nil
}
