// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_destructuring

import "github.com/go-json-experiment/json"

type DestructuringTypeConfig struct {
	// Array corresponds to the JSON schema field "array".
	Array *bool `json:"array,omitempty"`

	// Object corresponds to the JSON schema field "object".
	Object *bool `json:"object,omitempty"`
}

type PreferDestructuringOptions struct {
	// AssignmentExpression corresponds to the JSON schema field
	// "AssignmentExpression".
	AssignmentExpression *DestructuringTypeConfig `json:"AssignmentExpression,omitempty"`

	// VariableDeclarator corresponds to the JSON schema field "VariableDeclarator".
	VariableDeclarator *DestructuringTypeConfig `json:"VariableDeclarator,omitempty"`

	// Array corresponds to the JSON schema field "array".
	Array *bool `json:"array,omitempty"`

	// EnforceForDeclarationWithTypeAnnotation corresponds to the JSON schema field
	// "enforceForDeclarationWithTypeAnnotation".
	EnforceForDeclarationWithTypeAnnotation bool `json:"enforceForDeclarationWithTypeAnnotation,omitempty"`

	// EnforceForRenamedProperties corresponds to the JSON schema field
	// "enforceForRenamedProperties".
	EnforceForRenamedProperties bool `json:"enforceForRenamedProperties,omitempty"`

	// Object corresponds to the JSON schema field "object".
	Object *bool `json:"object,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferDestructuringOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferDestructuringOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["enforceForDeclarationWithTypeAnnotation"]; !ok || v == nil {
		plain.EnforceForDeclarationWithTypeAnnotation = false
	}
	if v, ok := raw["enforceForRenamedProperties"]; !ok || v == nil {
		plain.EnforceForRenamedProperties = false
	}
	*j = PreferDestructuringOptions(plain)
	return nil
}
