
// Code generated by tools/gen_shims. DO NOT EDIT.

package pnp

import "github.com/microsoft/typescript-go/internal/pnp"
import "github.com/microsoft/typescript-go/internal/vfs"
import _ "unsafe"

type PnpApi = pnp.PnpApi

//go:linkname InitPnpApi github.com/microsoft/typescript-go/internal/pnp.InitPnpApi
func InitPnpApi(fs vfs.FS, filePath string) *pnp.PnpApi

//go:linkname IsPnpLoaderFile github.com/microsoft/typescript-go/internal/pnp.IsPnpLoaderFile
func IsPnpLoaderFile(path string) bool
