name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
# Run on pull requests to see performance impact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install codspeed-go-runner from git
        run: cargo install --git https://github.com/codSpeedHQ/codspeed-go.git codspeed-go-runner

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          run: go test -bench ^BenchmarkHeadlessVueCore$ github.com/typescript-eslint/tsgolint/cmd/tsgolint
          token: ${{ secrets.CODSPEED_TOKEN }}
