name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
# Run on pull requests to see performance impact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # required for git am --3way to work properly
          submodules: true
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          run: go test -bench=. -run=^$ ./internal/utils ./internal/linter
          token: ${{ secrets.CODSPEED_TOKEN }}
