name: Save dprint plugin cache

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dprint.json"
      - ".github/workflows/dprint.yml"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: taiki-e/install-action@b18b9d93a43496aeda12369e7563d9251abc2fe1 # v2.68.24
        with:
          tool: dprint

      - run: dprint check

      - name: Save dprint plugin cache
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: dprint-${{ hashFiles('dprint.json') }}
          path: ~/.cache/dprint
